name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Theus090
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%238A2BE2&color_dots=%231C1C1C%23333333%23444444%23555555%236A0DAD
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2300BFFF&color_dots=%231C1C1C%23333333%23444444%23555555%238A2BE2

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
